### ISSUE TITLE
Argument -s/-seed: invalid int value: 'np'

### ISSUE THREAD

**Issue by carleshf** [dantaki/SV2#17]
Many thanks for the answer. I specified the SNP file, but the error I got
is about the `seed` argument:

The command:

``` 
sv2 \
    -bam /media/[...]/WGS/Fibroblast/Fibroblast_bwa_b38_recal_leftalignindels.hasLB.bam \
    -vcf /media/[...]/iPSC/lumpy_iPSC/Fibroblast_bwa_b38_recal_leftalignindels.hasLB.svtyper.vcf /media/[...]/iPSC/manta_fibroblast/results/variants/candidateSV.vcf.gz /media/[...]/iPSC/manta_fibroblast/results/variants/candidateSmallIndels.vcf.gz \
    -snv Fibroblast_bwa_b38_gatk3_hc.g.vcf.gz \
    -genome hg38 \
    -merge \
    -seed 26111234
```

​The error:

```
sv2: error: argument -s/-seed: invalid int value: 'np'
```

**Comment by carleshf** [comment]
In the end, I was able to run the `SV2`, but now I got an exception at the end of the execution.

My command:

```
time sv2 \
    -bam /media/NFS/Mclean_iPSC_WGS/Fibroblast/Fibroblast_bwa_b38_recal_leftalignindels.hasLB.bam \
    -snv /media/NFS/Mclean_iPSC_WGS/Fibroblast/Fibroblast_bwa_b38_gatk3_hc.vcf.gz \
    -ped /media/NFS/Carles/SV/iPSC/sv2_fibroblast_manta_lumpy/Fibroblast_bwa_b38_recal_leftalignindels.ped \
    -vcf /media/NFS/Carles/SV/iPSC/lumpy_iPSC/Fibroblast_bwa_b38_recal_leftalignindels.hasLB.svtyper.vcf \
    -log sv2_log
```

This is the error located at the end of the log:

```
/home/chernandez/anaconda2/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/home/chernandez/anaconda2/lib/python2.7/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/home/chernandez/anaconda2/bin/sv2", line 3, in <module>
    if __name__=='__main__': main()
  File "/home/chernandez/anaconda2/lib/python2.7/site-packages/sv2/sv2.py", line 208, in main
    extract_feats(bam,SV.raw,prefh,featfh,gen,pcrfree,legacy_m,Confs,tmp_dir)
  File "sv2/FeatureExtraction.pyx", line 16, in sv2.FeatureExtraction.extract_feats
  File "sv2/FeatureExtraction.pyx", line 144, in sv2.FeatureExtraction.filter_sv
KeyError: '1'
```

Content of `sv2_features` is empty. Content of `sv2_preprocessing` also shows empty content:

```
[carleshf@server sv2_fibroblast_manta_lumpy]$ cat sv2_preprocessing/Fibroblast_sv2_preprocessing.txt 
#id     chrom   coverage_median read_length_median      insert_size_median      insert_size_mad bam_bp_parsed   snv_depth_median        snv_parsed
Fibroblast      GENOME  nan     nan     nan     nan     0       0       0
```

And no result is generated.

**Comment by dantaki** [comment]
What platform/OS are you using? I  cannot replicate your `-seed` error. 

```
$ sv2 -i HG00096_sub.bam -snv HG00096_sub.vcf.gz -vcf 1kgp_phase3_tutorial.vcf -p HG00096.ped -seed 26111234 -merge
sv2 version:1.4.3    report bugs to <dantaki at ucsd dot edu>       error messages located in STDOUT
************************************************
 PREPROCESSING COMPLETE <time elapsed: 0:01:35>
************************************************
*****************************************************
 FEATURE EXTRACTION COMPLETE <time elapsed: 0:03:26>
*****************************************************
*********************************************
 GENOTYPING COMPLETE <time elapsed: 0:03:45>
*********************************************
```

The `KeyError` is complaining about a contig in your BAM file header. This doesn't make sense to me, because it uses the contig names from the BAM file
```
c = match_chrom_prefix(c,Bam.chr_flag) # chromosome matches ones in the BAM file
if c not in accepted_chrom(Bam.chr_flag,gen):
    sys.stderr.write('WARNING: Skipping {}. SV2 does not genotype SVs on contig {}\n'.format(r,c))
    continue
if skip_sv(c,s,e,cl,Bam.refs[c])==True: continue # this is the cause of the error
```

`Bam.refs` is an ordered dict taken from the pysam.AlignmentFile.references attribute (http://pysam.readthedocs.io/en/latest/api.html#pysam.AlignmentFile.references)

In sv2/Bam.py

```
#line 32
for i in range(len(bam.references)):
    chrom,leng = str(bam.references[i]),bam.lengths[i]
                if chrom in chroms: self.refs[chrom]=int(leng)
```

**I suspect your BAM file does not have any contig information in it. Here what the contig header information should look like using the SV2 tutorial bam file** 

```
$ samtools view HG00096_sub.bam -H  | grep "@SQ"
@SQ     SN:1    LN:249250621
@SQ     SN:2    LN:243199373
@SQ     SN:3    LN:198022430
@SQ     SN:4    LN:191154276
@SQ     SN:5    LN:180915260
@SQ     SN:6    LN:171115067
@SQ     SN:7    LN:159138663
@SQ     SN:8    LN:146364022
@SQ     SN:9    LN:141213431
@SQ     SN:10   LN:135534747
@SQ     SN:11   LN:135006516
@SQ     SN:12   LN:133851895
@SQ     SN:13   LN:115169878
@SQ     SN:14   LN:107349540
@SQ     SN:15   LN:102531392
@SQ     SN:16   LN:90354753
@SQ     SN:17   LN:81195210
@SQ     SN:18   LN:78077248
@SQ     SN:19   LN:59128983
@SQ     SN:20   LN:63025520
@SQ     SN:21   LN:48129895
@SQ     SN:22   LN:51304566
@SQ     SN:X    LN:155270560
@SQ     SN:Y    LN:59373566
     .....
```

What does your BAM file look like if your run the same command? It would make sense that it lacks the contig information since the preprocessing output is empty. The preprocessing step uses the contig header information.

**Comment by carleshf** [comment]
Many thanks for your answer. 

I'm using GNU/Linux CentOS 7. Here the results of the command you requested, we have this information into the header:

```
[carleshf@server sv2_fibroblast_manta_lumpy]$ samtools view /media/NFS/Mclean_iPSC_WGS/Fibroblast/Fibroblast_bwa_b38_recal_leftalignindels.hasLB.bam -H  | grep "@SQ" | head -10
@SQ     SN:chr1 LN:248956422
@SQ     SN:chr2 LN:242193529
@SQ     SN:chr3 LN:198295559
@SQ     SN:chr4 LN:190214555
@SQ     SN:chr5 LN:181538259
@SQ     SN:chr6 LN:170805979
@SQ     SN:chr7 LN:159345973
@SQ     SN:chr8 LN:145138636
@SQ     SN:chr9 LN:138394717
@SQ     SN:chr10        LN:133797422
```

May the problem be the identification of the chromosomes (`chr1` vs. `1`)?

**Comment by dantaki** [comment]
Weird, I ran that test on `Rocks 6.2 Sidewinder (CentOS 6.6)`. Can you run this test script I pasted in at the bottom and see if you get the appropriate output? 

# hg19 test

```
$ python test_pysam.py HG00096_sub.bam >tmp && head tmp 

1 chr not found
1 249250621
2 243199373
3 198022430
4 191154276
5 180915260
6 171115067
7 159138663
8 146364022
9 141213431
```

# hg38 test
```
$ python test_pysam.py HG00731.hg38.bam >tmp && head tmp 

chr1 chr prefix found
chr1 248956422
chr2 242193529
chr3 198295559
chr4 190214555
chr5 181538259
chr6 170805979
chr7 159345973
chr8 145138636
chr9 138394717
```
# test_pysam.py

```
import pysam,sys		
fh = sys.argv[1]
bam = pysam.AlignmentFile(fh)

if str(bam.references[0]).startswith('chr'): 
	print bam.references[0],'chr prefix found'
else: 
	print bam.references[0],'chr not found'
for i in range(len(bam.references)):
	chrom,leng = str(bam.references[i]),bam.lengths[i]
	print chrom,leng
bam.close()
```

It's really weird that SV2 is not detecting your contigs are prefixed with "chr" (as they should be in hg38). The `KeyError [1]` was indicating the bam.chr_flag is equal to False (not prefixed with 'chr') 

What version of pysam are you using? SV2 works for 0.14.1 and I think should work for versions 0.9 or greater... (maybe not and this could the cause of your error) 

```
$ pip show pysam
Name: pysam
Version: 0.14.1
Summary: pysam
Home-page: https://github.com/pysam-developers/pysam
Author: Andreas Heger
Author-email: andreas.heger@gmail.com
License: MIT
```

**Comment by carleshf** [comment]
Hi again!

About `pysam`:

```
[chernandez@t7600 sv2_fibroblast_manta_lumpy]$ pip show pysam
Name: pysam
Version: 0.14.1
Summary: pysam
Home-page: https://github.com/pysam-developers/pysam
Author: Andreas Heger
Author-email: andreas.heger@gmail.com
License: MIT
Location: /home/chernandez/anaconda2/lib/python2.7/site-packages
Requires: 
Required-by: sv2, svtyper
```

About the script you asked me:

```
[chernandez@t7600 sv2_fibroblast_manta_lumpy]$ python test_pysam.py /media/NFS/Mclean_iPSC_WGS/Fibroblast/Fibroblast_bwa_b38_recal_leftalignindels.hasLB.bam > tmp && head tmp 
chr1 chr prefix found
chr1 248956422
chr2 242193529
chr3 198295559
chr4 190214555
chr5 181538259
chr6 170805979
chr7 159345973
chr8 145138636
chr9 138394717
```

**Comment by dantaki** [comment]
Odd. I'm really at a loss here. I wrote SV2 so that it can handle chr/ or not prefixed BAMs (just in case a user opts for the "chr" prefixed hg19 assembly for example).

The `bam.chr_flag` is set according to the first `@SQ` entry and yours has a "chr" in it. So it should not produce the KeyError you're getting. The `chroms` from `def accepted_chrom(flag,gen)` in sv2_backend.py should produce a list with 'chr' prefixed in it.

There's something cryptic happening here, have you run the SV2 tutorial without error? Maybe give that a try, maybe something about the command line argument is throwing off the script, since the command line could not recognize your `seed` as an int?

https://github.com/dantaki/SV2/wiki/tutorial

 I kinda doubt this because in the main sv2.py script there's these commands that will kill the script if an unrecognized genome build is used:

```
if gen not in gens:
	print 'FATAL ERROR -g must be hg19 or hg38. NOT {}'.format(gen)
	sys.stderr.write('FATAL ERROR -g must be hg19 or hg38. NOT {}\n'.format(gen))
        sys.exit(1)
```

Sorry I can't help out more. I never came across this error and it hasn't been reported to me before.

**Comment by carleshf** [comment]
I was able to complete the tutorial:

```
[chernandez@t7600 sv2_tutorial]$ time sv2 -i HG00096_sub.bam       -v 1kgp_phase3_tutorial.vcf       -snv HG00096_sub.vcf.gz       -p HG00096.ped       -o HG00096_sv2
sv2 version:1.4.3.4    report bugs to <dantaki at ucsd dot edu>       error messages located in STDOUT
************************************************
 PREPROCESSING COMPLETE <time elapsed: 0:02:28>
************************************************
*****************************************************
 FEATURE EXTRACTION COMPLETE <time elapsed: 0:06:07>
*****************************************************
*********************************************
 GENOTYPING COMPLETE <time elapsed: 0:06:33>
*********************************************

real    6m42.510s
user    3m34.693s
sys     1m37.978s
```

So, or the problem is in my data or the problem is that I am not using properly `sv2`. My goal is to "merge" or to "collapse" the results from `lumpy`/`SVTyper` and `manta` (in a near future we will add more SV callers).

**Comment by dantaki** [comment]
You can try running SV2 on another BAM you have. I would bet that the fault is in your BAM somewhere. 

SV2 uses reciprocal overlap to collapse variants, this is the method that was largely used for microarray CNV calls and early analyses of SVs in WGS. Another method that we have applied more recently is collapsing on overlapping `CIPOS` and `CIEND` intervals, which works for SV callers that report these statistics. However there are limitations to this method too and I don't really plan on adding this feature to SV2 in the near future because of my limited bandwidth.
