### ISSUE TITLE
Error message does not output

### ISSUE THREAD

**Issue by sunnyzxh** [dantaki/SV2#18]
Hi
I got the title message with the following command, could you please help

mydir/sv2-1.4.3.3/sv2/sv2 -bam mydir/sampleA.recalibrated.bam -bed mydir/sampleA.DEL.overlap.bed -snv mydir/sampleA.vcf.gz -ped mydir/sampleA.ped -hg19 mydir/ref/ucsc.hg19.fasta -g hg19 -L sampleA.log 
sv2 version:1.4.3    report bugs to <dantaki at ucsd dot edu>       error messages located in sampleA.log

THANKS!!!

**Comment by dantaki** [comment]
Is the `sampleA.log` file empty? This file should contain an error message. 

Can you also update SV2 to 1.4.3.4
```
pip install sv2 --upgrade
```
If you installed with pip then you do not have to specify the full path to the SV2 script, running

```
$ sv2 -bam <in.bam> .... 
```
Should work, however I doubt this is the cause of your problem.

Have you run the SV2 tutorial without error? https://github.com/dantaki/SV2/wiki/tutorial

Is your fasta file indexed with `samtools faidx`? 

Check out those things and let me know if you still can't get SV2 to run. Also please indicate what platform/OS you are using and your version of python.

**Comment by sunnyzxh** [comment]
when I used the command pip install sv2 --upgrade to update sv2, and it seems still in the old version...

and I get the following error message when running the tutorial, with linux and Python 2.7.5, 

sv2 -i HG00096_sub.bam       -v 1kgp_phase3_tutorial.vcf       -snv HG00096_sub.vcf.gz       -p HG00096.ped       -o HG00096_sv2
sv2 version:1.4.3    report bugs to <dantaki at ucsd dot edu>       error messages located in STDOUT
Traceback (most recent call last):
  File "/home2/groups/paultam/sunny/bin/CNV/SV2/test/sv2-1.4.3.3/sv2/sv2", line 3, in <module>
    if __name__=='__main__': main()
  File "/home/groups2/paultam/sunny/bin/CNV/SV2/test/sv2-1.4.3.3/sv2/sv2.py", line 163, in main
    SV = sv_init(bed,vcf,gen)
  File "/home/groups2/paultam/sunny/bin/CNV/SV2/test/sv2-1.4.3.3/sv2/SV.py", line 78, in sv_init
    SV = Structural_Variant(sv,variant_id,gen)
  File "/home/groups2/paultam/sunny/bin/CNV/SV2/test/sv2-1.4.3.3/sv2/SV.py", line 8, in __init__
    self.raw=[(str(x[0]),int(x[1]),int(x[2]),str(x[3])) for x in BedTool(list(set(sv))).sort()]
  File "/home2/groups/paultam/sunny/bin/Python-2.7.3/site-packages/lib64/python2.7/site-packages/pybedtools-0.7.10-py2.7-linux-x86_64.egg/pybedtools/bedtool.py", line 806, in decorated
    result = method(self, *args, **kwargs)
  File "/home2/groups/paultam/sunny/bin/Python-2.7.3/site-packages/lib64/python2.7/site-packages/pybedtools-0.7.10-py2.7-linux-x86_64.egg/pybedtools/bedtool.py", line 204, in not_implemented_func
    raise NotImplementedError(help_str)
NotImplementedError: "sortBed" does not appear to be installed or on the path, so this method is disabled.  Please install a more recent version of BEDTools and re-import to use this method.

**Comment by dantaki** [comment]
You need a more recent version of Bedtools in your $PATH. 

SV2 requires Bedtools 2.25 or later

https://github.com/dantaki/SV2#requirements

Please check if you meet all the requirements, such as python 2.7+

**Comment by sunnyzxh** [comment]
Hi dantaki,

Thanks a lot! The problems I met above were solved, and the tutorial data were runned successfully. In my real data, the preprocessing and features were success, but I met the following error messages in the genotyping process, could you please help again?

/software/SV2/1.4.3/venv/lib/python2.7/site-packages/sv2-1.4.3.3-py2.7-linux-x86_64.egg/sv2/sv2.py:237: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  SVs = genotype(feats,outdir+ofh.replace('.vcf','.txt'),classifier_name,Peds,Confs,gen)
Traceback (most recent call last):
  File "/software/SV2/1.4.3/bin/sv2", line 4, in <module>
    __import__('pkg_resources').run_script('sv2==1.4.3.3', 'sv2')
  File "/software/SV2/1.4.3/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/software/SV2/1.4.3/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1434, in run_script
    exec(code, namespace, namespace)
  File "/software/SV2/1.4.3/venv/lib/python2.7/site-packages/sv2-1.4.3.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/sv2", line 3, in <module>
    if __name__=='__main__': main()
  File "/software/SV2/1.4.3/venv/lib/python2.7/site-packages/sv2-1.4.3.3-py2.7-linux-x86_64.egg/sv2/sv2.py", line 237, in main
    SVs = genotype(feats,outdir+ofh.replace('.vcf','.txt'),classifier_name,Peds,Confs,gen)
  File "sv2/Genotype.pyx", line 27, in sv2.Genotype.genotype
  File "sv2/Genotype.pyx", line 78, in sv2.Genotype.c_biallele_dels
  File "sv2/Svm.pyx", line

Thanks!

**Comment by dantaki** [comment]
I don't think you posted the full error message
```
/software/SV2/1.4.3/venv/lib/python2.7/site-packages/sv2-1.4.3.3-py2.7-linux-x86_64.egg

/sv2/sv2.py:237: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
```

Is just a warning. Was there more to the error message like a TypeError or something like that?
