### ISSUE TITLE
ValueError: could not create iterator for region 'X:2745094-2745111'

### ISSUE THREAD

**Issue by Varunachander** [dantaki/SV2#8]
Hi Dantaki,

I am facing the following issue while running SV2 on GiaB dataset. See traceback and error below:

Traceback (most recent call last):
  File "/users/chander/myproject/programs/Miniconda2/bin/sv2", line 3, in <module>
    if __name__=='__main__': main()
  File "/users/chander/myproject/programs/Miniconda2/lib/python2.7/site-packages/sv2/sv2.py", line 204, in main
    extract_feats(bam,SV.raw,prefh,featfh,gen,pcrfree,legacy_m,Confs,tmp_dir)
  File "sv2/FeatureExtraction.pyx", line 20, in sv2.FeatureExtraction.extract_feats
  File "sv2/Snv.pyx", line 34, in sv2.Snv.extract_snv_features
  File "sv2/Snv.pyx", line 69, in sv2.Snv.c_extract_snv_features
  File "pysam/libctabix.pyx", line 499, in pysam.libctabix.TabixFile.fetch
**ValueError: could not create iterator for region 'X:2745094-2745111'**

What do you think is going on here?

Best,
Varuna

**Comment by dantaki** [comment]
Can you check if your SNV file has chrX in it? Typically this error occurs because it attempts to tabix a region that's not present in the file

**Comment by Varunachander** [comment]
Hi Dantaki,

Thanks for the reply. I checked the SNV file and it does not have the chrX in it but neither any entry of X. Do you think that is the problem here?

Thanks very much!
Varuna

**Comment by dantaki** [comment]
Yes this error occurs when you have a structural variant on a contig that's not present in the SNV VCF. I think I resolved the issue with this commit 155e2b590c78ae0b507410a2e37fe2f4742f6fcf

please uninstall sv2 and re-install with `pip install sv2` 

Thank you
